#!/bin/bash
h=`date +%H`

if [ $h -lt 12 ]; then
  echo Good morning sir! Welcome back! 
elif [ $h -lt 18 ]; then
  echo Good afternoon sir! Welcome back!
else
  echo Good evening sir! Welcome back!
fi


